import { useState } from 'react';
import { format, formatDistanceToNow } from 'date-fns';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { 
  Table, 
  TableBody, 
  TableCell, 
  TableHead, 
  TableHeader, 
  TableRow 
} from '@/components/ui/table';
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from '@/components/ui/dropdown-menu';
import { Skeleton } from '@/components/ui/skeleton';
import { useAuditPacks } from '@/hooks/useAuditPacks';
import { AUDIT_PACK_LABELS, type AuditPackStatus } from '@/types/auditPacks';
import { 
  Download, 
  MoreHorizontal, 
  FileArchive, 
  Loader2,
  CheckCircle,
  XCircle,
  Clock,
  AlertTriangle,
} from 'lucide-react';

const statusConfig: Record<AuditPackStatus, { 
  label: string; 
  variant: 'default' | 'secondary' | 'destructive' | 'outline';
  icon: React.ComponentType<{ className?: string }>;
}> = {
  pending: { label: 'Pending', variant: 'secondary', icon: Clock },
  generating: { label: 'Generating', variant: 'default', icon: Loader2 },
  completed: { label: 'Completed', variant: 'default', icon: CheckCircle },
  failed: { label: 'Failed', variant: 'destructive', icon: XCircle },
  expired: { label: 'Expired', variant: 'outline', icon: AlertTriangle },
};

export function ExportHistory() {
  const { auditPacks, isLoading, getDownloadUrl, isDownloading } = useAuditPacks();
  const [downloadingId, setDownloadingId] = useState<string | null>(null);

  const handleDownload = async (packId: string, filePath: string) => {
    setDownloadingId(packId);
    try {
      const url = await getDownloadUrl(filePath);
      window.open(url, '_blank');
    } finally {
      setDownloadingId(null);
    }
  };

  if (isLoading) {
    return (
      <Card>
        <CardHeader>
          <CardTitle>Export History</CardTitle>
          <CardDescription>Previously generated audit packs</CardDescription>
        </CardHeader>
        <CardContent>
          <div className="space-y-3">
            {[1, 2, 3].map((i) => (
              <Skeleton key={i} className="h-16 w-full" />
            ))}
          </div>
        </CardContent>
      </Card>
    );
  }

  if (auditPacks.length === 0) {
    return (
      <Card>
        <CardHeader>
          <CardTitle>Export History</CardTitle>
          <CardDescription>Previously generated audit packs</CardDescription>
        </CardHeader>
        <CardContent>
          <div className="text-center py-12">
            <FileArchive className="h-12 w-12 mx-auto text-muted-foreground opacity-50" />
            <h3 className="mt-4 text-lg font-medium">No audit packs yet</h3>
            <p className="mt-2 text-sm text-muted-foreground">
              Generate your first audit pack using the builder tab
            </p>
          </div>
        </CardContent>
      </Card>
    );
  }

  return (
    <Card>
      <CardHeader>
        <CardTitle>Export History</CardTitle>
        <CardDescription>
          {auditPacks.length} audit pack{auditPacks.length !== 1 ? 's' : ''} generated
        </CardDescription>
      </CardHeader>
      <CardContent>
        <Table>
          <TableHeader>
            <TableRow>
              <TableHead>Pack Type</TableHead>
              <TableHead>Scope</TableHead>
              <TableHead>Generated By</TableHead>
              <TableHead>Status</TableHead>
              <TableHead>Created</TableHead>
              <TableHead>Expires</TableHead>
              <TableHead className="w-[80px]"></TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            {auditPacks.map((pack) => {
              const config = statusConfig[pack.status];
              const StatusIcon = config.icon;
              const isGenerating = pack.status === 'generating' || pack.status === 'pending';

              return (
                <TableRow key={pack.id}>
                  <TableCell>
                    <div className="font-medium">
                      {AUDIT_PACK_LABELS[pack.pack_type]}
                    </div>
                    {pack.include_restricted_content && (
                      <Badge variant="destructive" className="text-xs mt-1">
                        Includes Restricted
                      </Badge>
                    )}
                  </TableCell>
                  <TableCell>
                    <div className="text-sm">
                      {pack.employee_id ? 'Single Employee' : 'Organisation-wide'}
                    </div>
                    {pack.date_range_start && pack.date_range_end && (
                      <div className="text-xs text-muted-foreground">
                        {format(new Date(pack.date_range_start), 'MMM d, yyyy')} - {' '}
                        {format(new Date(pack.date_range_end), 'MMM d, yyyy')}
                      </div>
                    )}
                  </TableCell>
                  <TableCell>
                    <div className="text-sm">{pack.generated_by_name}</div>
                    <div className="text-xs text-muted-foreground">
                      {pack.generated_by_email}
                    </div>
                  </TableCell>
                  <TableCell>
                    <Badge variant={config.variant} className="flex items-center gap-1 w-fit">
                      <StatusIcon className={`h-3 w-3 ${isGenerating ? 'animate-spin' : ''}`} />
                      {config.label}
                    </Badge>
                    {pack.status === 'failed' && pack.error_message && (
                      <div className="text-xs text-destructive mt-1 max-w-[200px] truncate">
                        {pack.error_message}
                      </div>
                    )}
                  </TableCell>
                  <TableCell>
                    <div className="text-sm">
                      {format(new Date(pack.created_at), 'MMM d, yyyy')}
                    </div>
                    <div className="text-xs text-muted-foreground">
                      {format(new Date(pack.created_at), 'HH:mm')}
                    </div>
                  </TableCell>
                  <TableCell>
                    {pack.expires_at ? (
                      <div className="text-sm text-muted-foreground">
                        {formatDistanceToNow(new Date(pack.expires_at), { addSuffix: true })}
                      </div>
                    ) : (
                      <span className="text-muted-foreground">—</span>
                    )}
                  </TableCell>
                  <TableCell>
                    {pack.status === 'completed' && pack.file_urls.length > 0 ? (
                      <DropdownMenu>
                        <DropdownMenuTrigger asChild>
                          <Button variant="ghost" size="icon">
                            {downloadingId === pack.id ? (
                              <Loader2 className="h-4 w-4 animate-spin" />
                            ) : (
                              <MoreHorizontal className="h-4 w-4" />
                            )}
                          </Button>
                        </DropdownMenuTrigger>
                        <DropdownMenuContent align="end">
                          {pack.file_urls.map((url, idx) => {
                            const fileName = url.split('/').pop() || `File ${idx + 1}`;
                            return (
                              <DropdownMenuItem
                                key={url}
                                onClick={() => handleDownload(pack.id, url)}
                              >
                                <Download className="mr-2 h-4 w-4" />
                                {fileName}
                              </DropdownMenuItem>
                            );
                          })}
                        </DropdownMenuContent>
                      </DropdownMenu>
                    ) : (
                      <span className="text-muted-foreground">—</span>
                    )}
                  </TableCell>
                </TableRow>
              );
            })}
          </TableBody>
        </Table>
      </CardContent>
    </Card>
  );
}
