-- Create enum for audit pack types
CREATE TYPE public.audit_pack_type AS ENUM (
  'employee_compliance',
  'organisation_compliance',
  'hr_incidents',
  'payroll_verification'
);

-- Create enum for audit pack status
CREATE TYPE public.audit_pack_status AS ENUM (
  'pending',
  'generating',
  'completed',
  'failed',
  'expired'
);

-- Create audit_packs table
CREATE TABLE public.audit_packs (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  organisation_id UUID NOT NULL REFERENCES public.organisations(id) ON DELETE CASCADE,
  pack_type public.audit_pack_type NOT NULL,
  status public.audit_pack_status NOT NULL DEFAULT 'pending',
  
  -- Scope
  employee_id UUID REFERENCES public.employees(id) ON DELETE SET NULL,
  date_range_start DATE,
  date_range_end DATE,
  
  -- Options
  include_restricted_content BOOLEAN NOT NULL DEFAULT false,
  include_attachments BOOLEAN NOT NULL DEFAULT false,
  
  -- Generated by
  generated_by UUID NOT NULL,
  generated_by_name TEXT,
  generated_by_email TEXT,
  
  -- Results
  file_urls JSONB DEFAULT '[]'::jsonb,
  summary JSONB DEFAULT '{}'::jsonb,
  error_message TEXT,
  
  -- Retention
  retention_days INTEGER NOT NULL DEFAULT 90,
  expires_at TIMESTAMP WITH TIME ZONE,
  
  -- Timestamps
  started_at TIMESTAMP WITH TIME ZONE,
  completed_at TIMESTAMP WITH TIME ZONE,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

-- Enable RLS
ALTER TABLE public.audit_packs ENABLE ROW LEVEL SECURITY;

-- RLS Policies - Only admins can access audit packs
CREATE POLICY "Admins can view audit packs in their organisation"
  ON public.audit_packs
  FOR SELECT
  USING (
    has_role(auth.uid(), 'admin'::app_role) 
    AND user_belongs_to_org(auth.uid(), organisation_id)
  );

CREATE POLICY "Admins can create audit packs"
  ON public.audit_packs
  FOR INSERT
  WITH CHECK (
    has_role(auth.uid(), 'admin'::app_role)
    AND user_belongs_to_org(auth.uid(), organisation_id)
  );

CREATE POLICY "Admins can update audit packs in their organisation"
  ON public.audit_packs
  FOR UPDATE
  USING (
    has_role(auth.uid(), 'admin'::app_role)
    AND user_belongs_to_org(auth.uid(), organisation_id)
  );

-- No delete policy - packs expire automatically

-- Trigger for updated_at
CREATE TRIGGER update_audit_packs_updated_at
  BEFORE UPDATE ON public.audit_packs
  FOR EACH ROW
  EXECUTE FUNCTION public.update_updated_at_column();

-- Function to set expiry date on insert
CREATE OR REPLACE FUNCTION public.set_audit_pack_expiry()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  NEW.expires_at := NEW.created_at + (NEW.retention_days || ' days')::INTERVAL;
  RETURN NEW;
END;
$$;

CREATE TRIGGER set_audit_pack_expiry_trigger
  BEFORE INSERT ON public.audit_packs
  FOR EACH ROW
  EXECUTE FUNCTION public.set_audit_pack_expiry();

-- Function to expire old audit packs
CREATE OR REPLACE FUNCTION public.expire_audit_packs()
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  UPDATE public.audit_packs
  SET status = 'expired', updated_at = now()
  WHERE status = 'completed' 
    AND expires_at < now();
END;
$$;

-- Create secure storage bucket for audit packs
INSERT INTO storage.buckets (id, name, public)
VALUES ('audit-packs', 'audit-packs', false)
ON CONFLICT (id) DO NOTHING;

-- Storage policies - only admins can access
CREATE POLICY "Admins can upload audit packs"
  ON storage.objects
  FOR INSERT
  WITH CHECK (
    bucket_id = 'audit-packs' 
    AND has_role(auth.uid(), 'admin'::app_role)
  );

CREATE POLICY "Admins can view audit packs"
  ON storage.objects
  FOR SELECT
  USING (
    bucket_id = 'audit-packs' 
    AND has_role(auth.uid(), 'admin'::app_role)
  );

CREATE POLICY "Admins can delete expired audit packs"
  ON storage.objects
  FOR DELETE
  USING (
    bucket_id = 'audit-packs' 
    AND has_role(auth.uid(), 'admin'::app_role)
  );

-- Add index for faster queries
CREATE INDEX idx_audit_packs_org_id ON public.audit_packs(organisation_id);
CREATE INDEX idx_audit_packs_status ON public.audit_packs(status);
CREATE INDEX idx_audit_packs_expires_at ON public.audit_packs(expires_at);